[package]
name = "snicc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bstr = "1.12.0"
clap = { version = "4.5.47", features = ["derive"] }
lalrpop-util = "0.22.2"
logos = "0.15.1"

[build-dependencies]
lalrpop = "0.22.2"
